version: '2'
services:
  slack-markov:
    build: .
    volumes:
      - ./:/app
    links:
      - redis
    ports:
      - 8080:8080
    environment:
      - SLACK_TOKEN=tokenpls
  redis:
    image: redis:3.2
